WebApplication6/Controllers/CtoVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;
using System.Data.Entity;
using WebApplication6.Models.ViewModels;


namespace WebApplication6.Controllers
{
    public class CtoVController : Controller
    {
        
        private NorthwindEntities db = new NorthwindEntities();

        // GET: CtoV
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DemoViewData()
        {
            ViewData["Name"] = "Bruce";
            return View();
        }

        public ActionResult DemoViewBag()
        {
            ViewBag.Name = "Bruce2";
            return View();
        }

        public ActionResult DemoVDModel()
        {
            //ViewData["products"] = db.Products.ToList();
            ViewBag.products = db.Products.ToList();
            return View();
        }

        public ActionResult DemoStronglytyped()
        {
            return View(db.Products.ToList());
        }

        public ActionResult DemoInput()
        {
            return View();
        }

        public ActionResult CheckInput(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                TempData["Error"] = "no blank!";
                return RedirectToAction("DemoInput");
            }
            ViewBag.Name = name;
            return View();        
        }


        public ActionResult DemoInclude()
        {
            var products = db.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier);
            return View(products.ToList());      
                            
        }

        public ActionResult DemoSelectList()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "CompanyName");
            return View();
        }

        public ActionResult DemoMultiModelObject()
        {
            ViewBag.Author = "B12";
            ViewBag.Book = "MVC 5 book";
            ViewBag.Product = (from p in db.Products select p).Take(10).ToList();
            ViewBag.Category = (from c in db.Categories select c).Take(10).ToList();
            return View();
        }

        public ActionResult DemoViewModel()
        {
            return View(new ProductCategoryViewModel()
            {
                Name = "B34",
                Book = "Book34",
                Product = (from p in db.Products select p).Take(10).ToList(),
                Category = (from c in db.Categories select c).Take(10).ToList()
            });
        }

        public ActionResult DemoTuple()
        {
            var products = db.Products.ToList();
            var catedories = db.Categories.ToList();
            var suplliers = db.Suppliers.ToList();
            var tupleModel = new Tuple<List<Product>, List<Category>, List<Supplier>>
                (products, catedories, suplliers);
            return View(tupleModel);
        }

        public ActionResult DemoQueryString()
        {
            ViewBag.id = int.Parse(Request.QueryString["id"]);
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication6/Views/CtoV/CheckInput.cshtml
@{
    ViewBag.Title = "CheckInput";
}

<h2>CheckInput</h2>

<p>@ViewBag.Name</p>

WebApplication6/Views/CtoV/DemoInclude.cshtml
@model IEnumerable<WebApplication6.Models.Product>

@{
    ViewBag.Title = "DemoInclude";
}

<h2>DemoInclude</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuantityPerUnit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitsOnOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReorderLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discontinued)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier.CompanyName)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuantityPerUnit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitsInStock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitsOnOrder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReorderLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discontinued)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier.CompanyName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>

WebApplication6/Views/CtoV/DemoInput.cshtml
@{
    ViewBag.Title = "DemoInput";
}

<h2>DemoInput</h2>

<div>
    @using (Html.BeginForm("CheckInput", "CtoV"))
    {
        <input type="text" name="name" /><br/>
        <span style="color:red">@TempData["Error"]</span><br/>
        <input type="submit" value="SUBMIT" />
    }
</div>

WebApplication6/Views/CtoV/DemoMultiModelObject.cshtml
@using WebApplication6.Models;

<div>
    <ul>
        <li>@ViewBag.Author</li>
        <li>@ViewBag.Book</li>
    </ul>
</div>

<h3>ProductName</h3>
<ul>
    @foreach (var item in ViewBag.Product as List<Product>)
    {
        <li>
                @item.ProductName
        </li>
    }
</ul>

<h3>CategoryName</h3>
<ul>
    @foreach (var item in ViewBag.Category as List<Category>)
    {
        <li>
            @item.CategoryName
        </li>
    }
</ul>
@{
    ViewBag.Title = "DemoMultiModelObject";
}

<h2>DemoMultiModelObject</h2>

WebApplication6/Views/CtoV/DemoQueryString.cshtml
@{
    ViewBag.Title = "DemoQueryString";
}

<h2>DemoQueryString</h2>

<p>
    ID: @ViewBag.id
</p>

WebApplication6/Views/CtoV/DemoSelectList.cshtml
@model WebApplication6.Models.Product

@{
    ViewBag.Title = "DemoSelectList";
}

<h2>DemoSelectList</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, "SupplierID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityPerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsOnOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsOnOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsOnOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReorderLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReorderLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReorderLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discontinued, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Discontinued)
                    @Html.ValidationMessageFor(model => model.Discontinued, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication6/Views/CtoV/DemoStronglytyped.cshtml
@model IEnumerable<WebApplication6.Models.Product>
@{
    ViewBag.Title = "DemoStronglytyped";
}

<h2>DemoStronglytyped</h2>
<ul>
    @foreach (var item in Model)
    {
        <li>
            @item.ProductName
        </li>
    }
</ul>

WebApplication6/Views/CtoV/DemoTuple.cshtml
@using WebApplication6.Models;
@model Tuple<List<Product>, List<Category>, List<Supplier>>

@{
    ViewBag.Title = "DemoTuple";
}

<h2>DemoTuple</h2>

<h3>ProductName</h3>\
<ul>
    @* Item1 is List<Product>*@
    @foreach(var item in Model.Item1)
    {
        <li>
            @item.ProductName
        </li>
    }
</ul>

<h3>CategoryName</h3>
<ul>
    @foreach(var item in Model.Item2)
    {
        <li>
            @item.CategoryName
        </li>
    }
</ul>

<h3>SupplierName</h3>
<ul>
    @foreach(var item in Model.Item3)
    {
        <li>
            @item.CompanyName
        </li>
    }
</ul>

WebApplication6/Views/CtoV/DemoVDModel.cshtml
@using WebApplication6.Models;
@{
    ViewBag.Title = "DemoVDModel";
    
}

<h2>DemoVDModel</h2>

<ul>
    @foreach (var item in ViewBag.Products as List<Product>)
    {
        <li>
            @item.ProductName
        </li>
    }
</ul>

WebApplication6/Views/CtoV/DemoViewBag.cshtml
@{
    ViewBag.Title = "DemoViewBag";
}

<h2>DemoViewBag</h2>

@ViewBag.Name

WebApplication6/Views/CtoV/DemoViewModel.cshtml
@model WebApplication6.Models.ViewModels.ProductCategoryViewModel

@{
    ViewBag.Title = "DemoViewModel";
}

<h2>DemoViewModel</h2>

<div>
    <ul>
        <li>@Model.Name</li>
        <li>@Model.Book</li>
    </ul>
</div>

<h3>ProductName</h3>
<ul>
    @foreach (var item in Model.Product)
    {
        <li>
            @item.ProductName
        </li>
    }
</ul>

<h3>CategoryName</h3>
<ul>
    @foreach(var item in Model.Category)
    {
        <li>
            @item.CategoryName
        </li>
    }
</ul>